server:
  port: 8006
spring:
  application:
    name: consul-payment
  cloud:
    consul:
      # consul地址
      host: 192.168.1.150
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
        # 该服务地址
        hostname: localhost