server:
  port: 80
spring:
  application:
    name: consul-order
  cloud:
    consul:
      # consul注册中心地址
      host: 192.168.1.150
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
        # 该服务地址
        hostname: localhost