server:
  port: 8001
spring:
  application:
    name: payment-service # 该服务的名称 用于在注册中心注册服务时用
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver #mysql驱动包
    url: jdbc:mysql://localhost:3306/springCloud?useUnicode=true&charcaterEncoding=utf-8&useSSL=false
    username: root
    password: root
  # 服务链路监控
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
      #采样率值介于 0 到 1 之间，1 则表示全部采集 一般取0.5
      probability: 1
mybatis:
  mapper-locations: classpath:mapper/*.xml  # sql映射文件地址
  type-aliases-package: com.hulin.entities # 别名
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://localhost:7001/eureka # 当注册中心是单机版时 则只需要指定单机注册中心的地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版 则该服务需要注册进每个注册中心
  # 修改该服务在注册中心中Status栏中显式的主机名 需要spring-boot-starter-actuator包支撑
  instance:
    instance-id: payment8001
    # 当鼠标放到注册中心Status栏中服务的地址时 需要显示ip地址
    prefer-ip-address: true
    # 自我保护机制相关
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30）
    lease-renewal-interval-in-seconds: 1
    # Eureka服务端在收到最后一次心跳后等待时间上限 ，单位为秒（默认90） 超时将剔除服务
    lease-expiration-duration-in-seconds: 2